spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/springcloud?useUnicode=true&characterEncoding=utf-8
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

ribbon:
  ReadTimeout: 60000
  ConnectTimeout: 20000

zuul:
  host:
    connect-timeout-millis: 20000
    socket-timeout-millis: 60000

  routes:
    authservice:
      path: /uiservice/**
      # 示例curl -X POST -d username=admin -d password=admin http://localhost:80/user/user/login
      #    curl -X POST -d username=admin -d password=admin http://localhost:80/authservice/user/login
      serviceId: ui
      sensitiveHeaders: